# Generated by Django 3.2.9 on 2022-05-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('director', models.CharField(max_length=255, verbose_name='Директоры')),
                ('mamandar_sany', models.IntegerField(verbose_name='Мамандар саны')),
                ('created_at', models.DateField(verbose_name='Құрылған уақыты')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='laboratory/', verbose_name='Сурет')),
            ],
            options={
                'verbose_name': 'Зертхана',
                'verbose_name_plural': 'Зертханалар',
                'db_table': 'laboratory',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Есімі')),
                ('title', models.CharField(max_length=100, verbose_name='Тақырыбы')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=5000, verbose_name='Хабарлама')),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пікір',
                'verbose_name_plural': 'Пікірлер',
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Scientists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('surname', models.CharField(max_length=255, verbose_name='Тегі')),
                ('lauazym', models.CharField(max_length=255, verbose_name='Лауазымы')),
                ('ainalasu_salasy', models.CharField(max_length=255, verbose_name='Айналысу саласы')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='scientists/', verbose_name='Сурет')),
            ],
            options={
                'verbose_name': 'Ғалым',
                'verbose_name_plural': 'Ғалымдар',
                'db_table': 'scientists',
            },
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
            ],
            options={
                'verbose_name': 'Дәрі шөп түрі',
                'verbose_name_plural': 'Дәрі шөп түрлері',
                'db_table': 'tur',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Облыс')),
                ('district', models.CharField(max_length=255, verbose_name='Аудан')),
                ('tau_aty', models.CharField(max_length=255, verbose_name='Тау аты')),
                ('qoryq_aty', models.CharField(max_length=255, verbose_name='Қорық аты')),
                ('slug', models.SlugField()),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.laboratory', verbose_name='Жауапты зертхана')),
            ],
            options={
                'verbose_name': 'Аумақ',
                'verbose_name_plural': 'Аумақтар',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='DariShopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('description', models.TextField(verbose_name='Сипаттамасы')),
                ('count', models.IntegerField(verbose_name='Саны')),
                ('image', models.ImageField(upload_to='darishopter/', verbose_name='Сурет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жарияланған күні')),
                ('slug', models.SlugField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.region', verbose_name='Адрес')),
                ('scientists', models.ManyToManyField(to='mainapp.Scientists', verbose_name='Зерттеуші ғалымдар')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tur', verbose_name='Түрі')),
            ],
            options={
                'verbose_name': 'Дәрі шөп',
                'verbose_name_plural': 'Дәрі шөптер',
                'db_table': 'darishopter',
            },
        ),
    ]
