# Generated by Django 3.2.9 on 2022-05-25 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darishopter',
            name='qoldanui',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Қолдануы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientists',
            name='dariler',
            field=models.ManyToManyField(related_name='dari', to='mainapp.DariShopter', verbose_name='Зерттеген дәрілер'),
        ),
        migrations.AlterField(
            model_name='darishopter',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.region', verbose_name='Таралуы'),
        ),
        migrations.AlterField(
            model_name='region',
            name='qoryq_aty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Қорық аты'),
        ),
    ]
