# Generated by Django 3.2.9 on 2022-05-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220525_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.laboratory', verbose_name='Жауапты зертхана'),
        ),
        migrations.AlterField(
            model_name='region',
            name='tau_aty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тау аты'),
        ),
        migrations.AlterField(
            model_name='scientists',
            name='dariler',
            field=models.ManyToManyField(blank=True, null=True, related_name='dari', to='mainapp.DariShopter', verbose_name='Зерттеген дәрілер'),
        ),
        migrations.AlterField(
            model_name='scientists',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scientists/', verbose_name='Сурет'),
        ),
    ]
