# Generated by Django 3.2.9 on 2022-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220525_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='darishopter',
            name='anyqtama',
            field=models.TextField(blank=True, null=True, verbose_name='Анықтама'),
        ),
        migrations.AlterField(
            model_name='scientists',
            name='dariler',
            field=models.ManyToManyField(blank=True, related_name='dari', to='mainapp.DariShopter', verbose_name='Зерттеген дәрілер'),
        ),
    ]
